### ISSUE TITLE
Дата в crc-out.dat файле

### ISSUE THREAD

**Issue by YuriyPovodyryov** [da-nie/TMS320Make#1]
Неплохо бы в прошивочном _out-crc.dat_ файле перед последней строкой с crc видеть не нули, а дату-время создания в человечьем виде )
![Untitled](https://user-images.githubusercontent.com/21302035/66265265-60118500-e81c-11e9-8aad-9b5911157255.png)

**Comment by da-nie** [comment]
А уже сделал. Потом выложу. :)
